### ISSUE TITLE
Websocket connections

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#132]
I think we should only push on those websockets and communicate from the frontend to the backend with the traditional API. This will also mean that we can make slimmer clients (on low-end devices) which don't support websockets, which will be missing out on nice-to-haves but still would function as usual.
The most important thing websockets would enable us to do is live-refreshing the file list views if files get uploaded from other devices.

**Comment by TheHamloer** [comment]
@riesinger So you would suggest that if one client (in case the user has multiple instances of freecloud opened) does some action, for example moving a file, the server sends a websocket multicast to all instances with the new content of old_folder and new_folder? Because that way the clients could decide if the information is important for them or not and would not need to handle the change itself... Same thing could be done for a changed text file

**Comment by riesinger** [comment]
I would have thought this way simpler: 

- Client 1 is connected but idling in folder `/hello`
- Client 2 creates a file in `/hello`
- Server sends a simple "Folder `/hello` has been updated"
- Client 1 decides that it needs to refresh, so it GETs `/api/v1/path/hello`

Sending more information from the server would complicate things but could also save some round-trips. My initial thought was: Once you start sending data via websockets, why not move the whole API to websockets?

**Comment by TheHamloer** [comment]
Would be also a good concept :+1: but would you track in which folder Client 1 is? Probably not and send all updates right?

**Comment by riesinger** [comment]
Jup less awareness is more easyness :wink:

**Comment by TheHamloer** [comment]
Closed by #154
